### ISSUE TITLE
Can't install winreg_unicode library

### ISSUE THREAD

**Issue by WalrusPUNCH** [DanielStutzbach/winreg_unicode#1]
Collecting winreg_unicode
  Using cached https://files.pythonhosted.org/packages/ec/d8/af45d7b26178ac38228a20baf7977ddac442ba792f7e0532f3e21f3eb583/winreg_unicode-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.13.tar.gz
    Traceback (most recent call last):
      File "C:\Users\***\AppData\Local\Temp\pycharm-packaging\winreg-unicode\distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\***\AppData\Local\Temp\pycharm-packaging\winreg-unicode\setup.py", line 5, in <module>
        distribute_setup.use_setuptools()
      File "C:\Users\***\AppData\Local\Temp\pycharm-packaging\winreg-unicode\distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "C:\Users\***\AppData\Local\Temp\pycharm-packaging\winreg-unicode\distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "C:\Users\***\AppData\Local\Temp\pycharm-packaging\winreg-unicode\distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "C:\Users\***\AppData\Local\Programs\Python\Python37-32\Lib\urllib\request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Users\Vadim\AppData\Local\Programs\Python\Python37-32\Lib\urllib\request.py", line 531, in open
        response = meth(req, response)
      File "C:\Users\***\AppData\Local\Programs\Python\Python37-32\Lib\urllib\request.py", line 641, in http_response
        'http', request, response, code, msg, hdrs)
      File "C:\Users\***\AppData\Local\Programs\Python\Python37-32\Lib\urllib\request.py", line 569, in error
        return self._call_chain(*args)
      File "C:\Users\***\AppData\Local\Programs\Python\Python37-32\Lib\urllib\request.py", line 503, in _call_chain
        result = func(*args)
      File "C:\Users\***\AppData\Local\Programs\Python\Python37-32\Lib\urllib\request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in C:\Users\***\AppData\Local\Temp\pycharm-packaging\winreg-unicode\

My system:
python 3.7
pip 19.0.3
setuptools 41.0.0
 urllib3 1.24.2

Problem:
urllib.error.HTTPError: HTTP Error 403: SSL is required
Command "python setup.py egg_info" failed with error code 1

How I can fix it? Thanks.

**Comment by dldudgns** [comment]
I'm getting a similar error, did you manage to find a fix for this?
